review:
  mode: incremental
  summarize: true
  max_comments: 40
  suggestions: concise
  only_changed_files: true
  diff_from: 'merge-base'
paths:
  include:
    - app/**
    - components/**
    - hooks/**
    - lib/**
    - pages/**
    - src/**
    - types/**
  exclude:
    - node_modules/**
    - dist/**
    - .next/**
    - out/**
    - coverage/**
    - .github/**
    - public/**
    - tests/**
    - test-results/**
    - playwright-report/**
    - dashboard-build/**
    - docs/**
    - Reports/**
    - '**/*.md'
    - '**/*.txt'
    - '**/*.mdx'
    - '**/*.csv'
