# Exclude non-code and generated files from CodeRabbit reviews
exclude:
  # Docs and text
  - "docs/**"
  - "Main Shop Imp/**"
  - "**/*.md"
  - "**/*.mdx"
  - "**/*.txt"
  - "**/*.log"
  - "**/*.csv"
  - "**/*.http"
  - "**/*.sql"

  # GitHub/IDE
  - ".github/**"
  - ".vscode/**"

  # Static/public assets (adjust if you want images reviewed)
  - "public/**"

  # Build & deps
  - ".next/**"
  - "out/**"
  - "node_modules/**"
  - ".turbo/**"
  - ".eslintcache"

  # Test artifacts
  - "coverage/**"
  - "test-results/**"
  - ".playwright-report/**"
