[build]
  command = "pnpm build"
  publish  = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Redirect hygiene (keep Next defaults; add static and 404 safety)
[[redirects]]
  from = "/_next/*"
  to   = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/404"
  status = 404
