name: E2E Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Build app
        run: pnpm build
      - name: Run E2E Tests
        env:
          # Provide required envs or use defaults from .env.local if repository includes it
          NEXT_PUBLIC_SITE_URL: http://127.0.0.1:3001
        run: pnpm test:e2e
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: test-results/Dashboard Report/html-report
      - name: Upload JSON results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-json
          path: test-results/Dashboard Report/test-results.json
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: test-results/Dashboard Report/test-artifacts
